---
title: "SPARQL query using Shiny to build interface"
author: "PhuseSubTeamAnalysisResults@example.org"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SPARQL query using Shiny to build interface}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---


## Prelimnaries
write more here
Here should be more text.
## Code


```{r echo =TRUE,eval=FALSE}

library (rrdf)
library(rrdfqbcrnd0)

doquery=function(query, endpoint){
  # prefix hard coded for now ... should be a parameter MJA 21-oct-2014
  myprefixes= list(
    "rdf"= "http://www.w3.org/1999/02/22-rdf-syntax-ns#" ,
    "skos"="http://www.w3.org/2004/02/skos/core#" ,
    "prov"="http://www.w3.org/ns/prov#" ,
    "rdfs"="http://www.w3.org/2000/01/rdf-schema#" ,
    "dcat"="http://www.w3.org/ns/dcat#" ,
    "owl"= "http://www.w3.org/2002/07/owl#" ,
    "xsd"= "http://www.w3.org/2001/XMLSchema#" ,
    "qb"=  "http://purl.org/linked-data/cube#" ,
    "pav"= "http://purl.org/pav" ,
    "dct"= "http://purl.org/dc/terms/" ,
    "mms"= "http://rdf.cdisc.org/mms#" ,
    "cts"= "http://rdf.cdisc.org/ct/schema#" 
  )  ;
  forsparqlprefix= paste("prefix", 
                         paste(names(myprefixes),":",sep=""), 
                         paste("<",myprefixes,">",sep=""),
                         sep=" ",collapse=" ")
  
  
  ## ------------------------------------------------------------------------
  
  prefquery = paste0( forsparqlprefix, query, sep=" ")
  queryresult= sparql.remote(endpoint, prefquery, jena=TRUE);
  
}

do_sparql <- function(var) {
  library(shiny)
  shinyApp(
    ui = fluidPage(
  titlePanel("SPARQL query"),
  fluidRow(
      HTML('<label for="query">SPARQL query:</label>'),
      tags$textarea(id="query", rows=5, style="width:90%", "select * where {?s ?p ?o} limit 10"),
      HTML('<label for="endpoint">SPARQL endpoint:</label>'),
#      tags$textarea(id="endpoint", rows=1, style="width:90%", "http://www.datadriven.jp:3030/cdisc/sparql"),
      tags$textarea(id="endpoint", rows=1, style="width:90%", "http://localhost:3030/cdisc/query"),
      submitButton("Submit")
    ), 
  fluidRow(
      h3(textOutput("query", container = span)),
     tableOutput("queryresult")
    )
      ),
    server = function(input, output) {
output$query= renderText(paste0(input$query));
output$queryresult= renderTable(doquery(input$query,input$endpoint));
    }
  )
}

```

When creating vignettes the code hangs. Hence the code is disabled.

Use eval=TRUE to get it to run. Note that it the shiny app does not respond, try to run it in a browser.

```{r eval=FALSE}
do_sparql("aa")
```
