## @knitr DEMOobservations  
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
prefix skos: <http://www.w3.org/2004/02/skos/core#>  
prefix prov: <http://www.w3.org/ns/prov#>  
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>  
prefix dcat: <http://www.w3.org/ns/dcat#>  
prefix owl: <http://www.w3.org/2002/07/owl#>  
prefix xsd: <http://www.w3.org/2001/XMLSchema#>  
prefix qb: <http://purl.org/linked-data/cube#>  
prefix pav: <http://purl.org/pav>  
prefix dct: <http://purl.org/dc/terms/>  
prefix mms: <http://rdf.cdisc.org/mms#>  
prefix cts: <http://rdf.cdisc.org/ct/schema#>  
prefix rrdfqbcrnd0: <http://www.example.org/rrdfqbcrnd0/>  
prefix code: <http://www.example.org/dc/code/>  
prefix dccs: <http://www.example.org/dc/demo/dccs/>  
prefix ds: <http://www.example.org/dc/demo/ds/>  
prefix crnd-dimension: <http://www.example.org/dc/dimension#>  
prefix crnd-attribute: <http://www.example.org/dc/attribute#>  
prefix crnd-measure: <http://www.example.org/dc/measure#>  

CONSTRUCT { ?s ?p ?o } 
where { ?s a qb:Observation ; ?p ?o .
values (?s) { (ds:obs014) } }
