##' rrdfqb.
##'
##' @name rrdfqb
##' @docType package
## documentation for dataset
NULL

##' 
##' Package locale environment
##'
##' @docType data
##' @name env
NULL

##' RDF data cube Integrity Constraints SPARQL queries
##'
##' A dataset containing the RDF data cube Integrity Constraints
##' SPARQL queries as a list. The dataset is generated by the script
##' \file{data-raw/create-qb-IC-dataset.Rmd}
##'
##' @docType data
##' @keywords datasets
##' @name qbIClist
## @usage data(qbIClist)
##' @format A list with SPARQL queries
##' @references \url{http://www.w3.org/TR/2014/REC-vocab-data-cube-20140116/}
NULL

