---
title: "Create queries for use with CDISC standards in RDF"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  md_document:
    variant: markdown_github

---

# Create SPARQL Queries for use with CDISC standards in RDF

## Setup 
```{r}
library(rrdfancillary)
library(devtools)
devtools::load_all(pkg="../..")
```

### Query for extracting codelist

The function `GetCDISCCodeListSparqlQuery` takes the codelist IRI as parameter and returns a query as a string.
Here the query is made for NCI code C66731, gender. The query is written to a file, so it can be used in other programs.

```{r, results='asis', eval=TRUE}
nciDomainValue<- "sdtmct:C66731"
query.rq <- GetCDISCCodeListSparqlQuery( Get.rq.prefixlist.df(qbCDISCprefixes), nciDomainValue )
cat(query.rq,"\n")
```

```{r, results='asis', eval=TRUE}
targetFile<- file.path(system.file("extdata/CDISC-standards-rdf", package="rrdfcdisc"),"CDISC-code-list-C66731.rq" )
writeLines( query.rq, con=targetFile )
cat("SPARQL script copied to ", normalizePath(targetFile), "\n")
```


### Template query for extracting codelist


```{r, results='asis', eval=TRUE}
nciDomainValue<- "$nciDomainValue"
query.rq <- GetCDISCCodeListSparqlQuery( Get.rq.prefixlist.df(qbCDISCprefixes), nciDomainValue )
cat(query.rq,"\n")
```

```{r, results='asis', eval=TRUE}
targetFile<- file.path(system.file("extdata/CDISC-standards-rdf", package="rrdfcdisc"),"CDISC-code-list-param.rq" )
writeLines( query.rq, con=targetFile )
cat("SPARQL script copied to ", normalizePath(targetFile), "\n")
```


