---
title: "Presenting RDF data cube for CDISC pilot project table 14-1.01"
author: "PhuseSubTeamAnalysisResults@example.org"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  md_document:
    variant: markdown_github
---

# Setup

First load the package.
```{r, eval=TRUE}
library(rrdf)
library(rrdfqb)
library(rrdfqbcrnd0)
library(rrdfqbcrndex)
library(rrdfqbpresent)
```



### Check GetTwoDimTableFromQb

```{r, eval=TRUE}
dataCubeFile<- system.file("extdata/sample-rdf", "CDISC-pilot-TAB1X01.ttlDC-DEMO-sample.ttl", package="rrdfqbcrndex")
store <- new.rdf(ontology=FALSE)  # Initialize
cat("Loading ", dataCubeFile, "\n")
temp<-load.rdf(dataCubeFile, format="TURTLE", appendTo= store)
dsdName<- GetDsdNameFromCube( store )
domainName<- GetDomainNameFromCube( store )
forsparqlprefix<- GetForSparqlPrefix( domainName )
cat("dsdName: ", dsdName, "\n")
cat("domainName: ", domainName, "\n")
cat("forsparqlprefix: ", forsparqlprefix, "\n")

dimensionsRq <- GetDimensionsSparqlQuery( forsparqlprefix )
dimensions<- sparql.rdf(store, dimensionsRq)

attributesRq<- GetAttributesSparqlQuery( forsparqlprefix )
attributes<- sparql.rdf(store, attributesRq)

observationsDescriptionRq<- GetObservationsWithDescriptionSparqlQuery( forsparqlprefix, domainName, dimensions, attributes )
observationsDesc<- as.data.frame(sparql.rdf(store, observationsDescriptionRq ), stringsAsFactors=FALSE)

coldim<- c("crnd-dimension:trt01p" )
rowdim<- c( "crnd-dimension:disconfl", "crnd-dimension:comp24fl",
           "crnd-dimension:ittfl",  "crnd-dimension:efffl",
           )

zdim<- c("crnd-dimension:procedure")

```

### View a specific observation.

First show the observations identifier.

```{r, eval=TRUE}
cube.observationsURI.rq<-  paste( forsparqlprefix,
'
select distinct ?s
where { 
?s a qb:Observation ; 
}
order by ?s
',
"\n"                               
)

cube.observationsURI<- sparql.rdf(store, cube.observationsURI.rq)
paste(cube.observationsURI)
```

The observation is specified in the values part of the SPARQL query.

```{r, eval=TRUE}
cube.observations.rq<-  paste( forsparqlprefix,
'
select *
where { 
?s a qb:Observation ; 
?p ?o .
values (?s) {
(',
cube.observationsURI[1],
')
}
}
',
"\n"                               
)

cube.observations<- sparql.rdf(store, cube.observations.rq)
knitr::kable(cube.observations)

```


# Making a query showing the columns

```{r, eval=TRUE}
cube.res.rq<-  paste(
#    gsub("prefix ds: .+$", "", forsparqlprefix),
forsparqlprefix,
'
select
 ?ittflVarLabel       ?ittflLevelLabel       ?ittfl
 ?safflVarLabel       ?safflLevelLabel       ?saffl
 ?effflVarLabel       ?effflLevelLabel       ?efffl
 ?comp24flVarLabel    ?comp24flLevelLabel    ?comp24fl
 ?disconflVarLabel    ?disconflLevelLabel    ?disconfl
 ?procedureZ1VarLabel ?procedureZ1LevelLabel ?procedureZ1  
 ?procedureZ2VarLabel ?procedureZ2LevelLabel ?procedureZ2  

 ?col1z1URI ?col1z1  ?col1z2URI ?col1z2
 ?col2z1URI ?col2z1  ?col2z2URI ?col2z2
 ?col3z1URI ?col3z1  ?col3z2URI ?col3z2
where
{
?col1z1URIx  a qb:Observation;
        crnd-dimension:comp24fl ?comp24fl    ;
        crnd-dimension:disconfl ?disconfl    ;
        crnd-dimension:efffl ?efffl       ;
        crnd-dimension:factor ?factorZ1      ;
        crnd-dimension:ittfl ?ittfl       ;
        crnd-dimension:procedure ?procedureZ1 ;   
        crnd-dimension:saffl ?saffl    ;
        crnd-dimension:trt01p code:trt01p-Placebo ;
        crnd-measure:measure ?col1z1 .

 ?col1z2URIx  a qb:Observation;
         crnd-dimension:comp24fl ?comp24fl    ;
         crnd-dimension:disconfl ?disconfl    ;
         crnd-dimension:efffl ?efffl       ;
         crnd-dimension:factor ?factorZ2      ;
         crnd-dimension:ittfl ?ittfl       ;
         crnd-dimension:procedure ?procedureZ2 ;   
         crnd-dimension:saffl ?saffl    ;
         crnd-dimension:trt01p code:trt01p-Placebo ;
         crnd-measure:measure ?col1z2 .

 ?col2z1URIx  a qb:Observation;
         crnd-dimension:comp24fl ?comp24fl    ;
         crnd-dimension:disconfl ?disconfl    ;
         crnd-dimension:efffl ?efffl       ;
         crnd-dimension:factor ?factorZ1      ;
         crnd-dimension:ittfl ?ittfl       ;
         crnd-dimension:procedure ?procedureZ1 ;   
         crnd-dimension:saffl ?saffl    ;
         crnd-dimension:trt01p code:trt01p-Xanomeline_Low_Dose ;
         crnd-measure:measure ?col2z1 .

 ?col2z2URIx  a qb:Observation;
         crnd-dimension:comp24fl ?comp24fl    ;
         crnd-dimension:disconfl ?disconfl    ;
         crnd-dimension:efffl ?efffl       ;
         crnd-dimension:factor ?factorZ2      ;
         crnd-dimension:ittfl ?ittfl       ;
         crnd-dimension:procedure ?procedureZ2 ;   
         crnd-dimension:saffl ?saffl    ;
         crnd-dimension:trt01p code:trt01p-Xanomeline_Low_Dose ;
         crnd-measure:measure ?col2z2 .

 ?col3z1URIx  a qb:Observation;
         crnd-dimension:comp24fl ?comp24fl    ;
         crnd-dimension:disconfl ?disconfl    ;
         crnd-dimension:efffl ?efffl       ;
         crnd-dimension:factor ?factorZ1      ;
         crnd-dimension:ittfl ?ittfl       ;
         crnd-dimension:procedure ?procedureZ1 ;   
         crnd-dimension:saffl ?saffl    ;
         crnd-dimension:trt01p code:trt01p-Xanomeline_High_Dose ;
         crnd-measure:measure ?col3z1 .

 ?col3z2URIx  a qb:Observation;
         crnd-dimension:comp24fl ?comp24fl    ;
         crnd-dimension:disconfl ?disconfl    ;
         crnd-dimension:efffl ?efffl       ;
         crnd-dimension:factor ?factorZ2      ;
         crnd-dimension:ittfl ?ittfl       ;
         crnd-dimension:procedure ?procedureZ2 ;   
         crnd-dimension:saffl ?saffl    ;
         crnd-dimension:trt01p code:trt01p-Xanomeline_High_Dose ;
         crnd-measure:measure ?col3z2 .


?comp24fl skos:prefLabel    ?comp24flLevelLabel .
?disconfl skos:prefLabel    ?disconflLevelLabel .
?efffl    skos:prefLabel    ?effflLevelLabel .
?ittfl    skos:prefLabel    ?ittflLevelLabel .
?saffl    skos:prefLabel    ?safflLevelLabel .
?procedureZ1 skos:prefLabel ?procedureZ1LevelLabel .
?procedureZ2 skos:prefLabel ?procedureZ2LevelLabel .

[] qb:codeList [ skos:hasTopConcept ?comp24fl ] ;
   rdfs:label ?comp24flVarLabel .

[] qb:codeList [ skos:hasTopConcept ?disconfl ] ;
   rdfs:label ?disconflVarLabel .

[] qb:codeList [ skos:hasTopConcept ?efffl ] ;
    rdfs:label ?effflVarLabel .

[] qb:codeList [ skos:hasTopConcept ?ittfl ] ;
   rdfs:label ?ittflVarLabel .

[] qb:codeList [ skos:hasTopConcept ?saffl ] ;
   rdfs:label ?safflVarLabel .

[] qb:codeList [ skos:hasTopConcept ?procedureZ1 ] ;
   rdfs:label ?procedureZ1VarLabel .

[] qb:codeList [ skos:hasTopConcept ?procedureZ2 ] ;
   rdfs:label ?procedureZ2VarLabel .


{ select * where { values(?factorZ1 ?procedureZ1 ?factorZ2 ?procedureZ2) {
(code:factor-quantity code:procedure-count code:factor-proportion code:procedure-percent)
} } }

 BIND( str(?col1z1URIx) as ?col1z1URI )
 BIND( str(?col2z1URIx) as ?col2z1URI )
 BIND( str(?col3z1URIx) as ?col3z1URI )

 BIND( str(?col1z2URIx) as ?col1z2URI )
 BIND( str(?col2z2URIx) as ?col2z2URI )
 BIND( str(?col3z2URIx) as ?col3z2URI )

 filter (
 ?ittfl = code:ittfl-Y ||
 ?saffl = code:saffl-Y||
 ?efffl = code:efffl-Y ||
 ?comp24fl = code:comp24fl-Y ||
 ?disconfl = code:disconfl-Y
 )
}
order by
?ittflLevelLabel ?safflLevelLabel ?effflLevelLabel ?comp24flLevelLabel ?disconflLevelLabel
',
"\n"                               
)

cube.res<- sparql.rdf(store, cube.res.rq)

knitr::kable(cube.res)


varlabels<- cube.res[1,c("ittflVarLabel",   "safflVarLabel",   "effflVarLabel",   "comp24flVarLabel",   "disconflVarLabel"   )]
varorder<- apply( cube.res[,c("ittflLevelLabel", "safflLevelLabel", "effflLevelLabel", "comp24flLevelLabel", "disconflLevelLabel"  )]=="Y",1, which)

present.res<- cbind(
    varlabels[varorder],
    cube.res[,c("col1z1", "col1z2", "col2z1", "col2z2", "col3z1", "col3z2")]
)
knitr::kable(present.res)
 
```


# Session information
```{r, echo=TRUE}
sessionInfo()
```

