---
title: "Two dimensional representation of RDF data cube"
author: "PhuseSubTeamAnalysisResults@example.org"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  md_document:
    variant: markdown_github
---

# Setup

First load the package.
```{r, eval=TRUE}
library(rrdf)
library(rrdfqb)
library(rrdfqbcrnd0)
library(rrdfqbcrndex)
library(rrdfqbpresent)
```



### Check GetTwoDimTableFromQb

```{r, eval=TRUE}
dataCubeFile<- system.file("extdata/sample-rdf", "DC-DEMO-sample.ttl", package="rrdfqbcrndex")
store <- new.rdf()  # Initialize
cat("Loading ", dataCubeFile, "\n")
temp<-load.rdf(dataCubeFile, format="TURTLE", appendTo= store)
dsdName<- GetDsdNameFromCube( store )
domainName<- GetDomainNameFromCube( store )
forsparqlprefix<- GetForSparqlPrefix( domainName )
cat("dsdName: ", dsdName, "\n")
cat("domainName: ", domainName, "\n")
cat("forsparqlprefix: ", forsparqlprefix, "\n")

coldim<- c("crnd-attribute:colno", "crnd-attribute:cellpartno", "crnd-dimension:trt01a" )
rowdim<- c("crnd-attribute:rowno", "crnd-dimension:agegr1", "crnd-dimension:race",
           "crnd-dimension:ethnic", "crnd-dimension:sex", "crnd-dimension:procedure" )
xqbtest<- GetTwoDimTableFromQb( store, forsparqlprefix, domainName, rowdim, coldim )

dimensionsRq <- GetDimensionsSparqlQuery( forsparqlprefix )
dimensions<- sparql.rdf(store, dimensionsRq)

attributesRq<- GetAttributesSparqlQuery( forsparqlprefix )
attributes<- sparql.rdf(store, attributesRq)

observationsDescriptionRq<- GetObservationsWithDescriptionSparqlQuery( forsparqlprefix, domainName, dimensions, attributes )
observationsDesc<- as.data.frame(sparql.rdf(store, observationsDescriptionRq ), stringsAsFactors=FALSE)


```

### View a specific observation.

The observation is specified in the values part of the SPARQL query.

```{r, eval=TRUE}

cube.observations.rq<-  paste( forsparqlprefix,
'
select *
where { 
?s a qb:Observation ; 
?p ?o .
values (?s) {
(ds:obs029)
}
}
',
"\n"                               
)

cube.observations<- sparql.rdf(store, cube.observations.rq)
knitr::kable(cube.observations)

```

### View formating of measure

```{r, eval=TRUE}
cube.measurefmt.rq<-  paste( forsparqlprefix,
'
select distinct ?procedure ?measurefmt
where { 
?s a qb:Observation ; 
crnd-dimension:procedure ?procedure ;
crnd-attribute:measurefmt ?measurefmt .
}
',
"\n"                               
)

cube.measurefmt<- sparql.rdf(store, cube.measurefmt.rq)
knitr::kable(cube.measurefmt)

```

### Columns

The contents of the 
```{r, echo=TRUE}
cols.rq<- GetRownoColnoCellpartnoSparqlQuery( forsparqlprefix )
cols<- data.frame(sparql.rdf(store, cols.rq))
knitr::kable(cols)

```


# Session information
```{r, echo=TRUE}
sessionInfo()
```

