---
title: "Execute SPARQL integrity constraints on a data cube"
author: "mja@statgroup.dk"
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{Execute SPARQL integrity constraints on a data cube}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## Checking two existing cube

```{r, results='asis', eval=TRUE}
library(rrdf)
library(rrdfqb)

cube.vocabulary.ttl <- file.path(system.file("extdata/cube-vocabulary-rdf", "cube.ttl", package="rrdfqb") )
cubevoc<- load.rdf( cube.vocabulary.ttl, format="TURTLE" )

qbfile1<- system.file("extdata/sample-rdf", "example.ttl", package="rrdfqb")
cube1<- load.rdf( qbfile1, format="TURTLE")

cubeData1<- combine.rdf( cube1, cubevoc)
forsparqlprefix<-'
prefix rdf:            <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:           <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:            <http://www.w3.org/2002/07/owl#>
prefix xsd:            <http://www.w3.org/2001/XMLSchema#>
prefix skos:           <http://www.w3.org/2004/02/skos/core#>
prefix foaf:           <http://xmlns.com/foaf/0.1/>
prefix scovo:          <http://purl.org/NET/scovo#>
prefix void:           <http://rdfs.org/ns/void#>
prefix qb:             <http://purl.org/linked-data/cube#>
prefix dcterms:        <http://purl.org/dc/terms/>

prefix void:     <http://rdfs.org/ns/void#>
prefix dct:      <http://purl.org/dc/terms/>
prefix org:      <http://www.w3.org/ns/org#>
prefix admingeo: <http://data.ordnancesurvey.co.uk/ontology/admingeo/>
prefix interval: <http://reference.data.gov.uk/def/intervals/>


prefix sdmx-concept:    <http://purl.org/linked-data/sdmx/2009/concept#>
prefix sdmx-dimension:  <http://purl.org/linked-data/sdmx/2009/dimension#>
prefix sdmx-attribute:  <http://purl.org/linked-data/sdmx/2009/attribute#>
prefix sdmx-measure:    <http://purl.org/linked-data/sdmx/2009/measure#>
prefix sdmx-metadata:   <http://purl.org/linked-data/sdmx/2009/metadata#>
prefix sdmx-code:       <http://purl.org/linked-data/sdmx/2009/code#>
prefix sdmx-subject:    <http://purl.org/linked-data/sdmx/2009/subject#>

prefix ex-geo:   <http://example.org/geo#>
prefix eg:       <http://example.org/ns#>
'

icres1<- RunQbIC( cubeData1, forsparqlprefix )
knitr::kable(icres1)
```

The file example-fails-IC14.ttl is example.ttl with a few triples added to make the cube non conformant with the intregity constaints.

```{r, results='asis', eval=TRUE}
qbfile2<- system.file("extdata/sample-rdf", "example-fails-IC14.ttl", package="rrdfqb")
cube2<- load.rdf( qbfile2, format="TURTLE")

cube.vocabulary.ttl <- file.path(system.file("extdata/cube-vocabulary-rdf", "cube.ttl", package="rrdfqb") )
cubevoc<- load.rdf( cube.vocabulary.ttl, format="TURTLE" )

cubeData2<- combine.rdf( cube2, cubevoc)

icres2<- RunQbIC( cubeData2, forsparqlprefix, doForIC=c("ic-14") )
knitr::kable(icres2)
```

